blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include(('magazine.urls', 'magazine'), namespace='magazine')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazine/urls.py
from django.urls import path
from .views import HomeView, PostView, PostCreateView, PostDeleteView, PostUpdateView, UserPostView, AdminPage, CommentDeleteView, AllPostsView, AdminPostDeleteView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('posts/', AllPostsView.as_view(), name='posts'),
    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('users/user-posts/', UserPostView.as_view(), name='user_posts'),
    path('admin-page/', AdminPage.as_view(), name='admin_page'),
    path('<int:pk>/admin-page/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('<int:pk>/admin-page/delete-post/', AdminPostDeleteView.as_view(), name='admin_post_delete'),
]

users/urls.py
from django.urls import path, reverse_lazy
from . views import signup, loginUser, logoutUser, profile, AboutMeForm, edit_user_profile
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profile, name='profile'),
    path('about_user/', edit_user_profile, name='about_user'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]

magazine/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True, db_index=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)
    article_description = models.CharField(max_length=200, null=True)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='', blank=True, null=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


# Rouizi
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

magazine/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')

magazine/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm
from .models import Post, Comment


class HomeView(ListView):
    """
    This class shows all posts, and adds the newest post on top of the page.
    The posts are ordered by date in decreasing order.
    """

    template_name = 'magazine/home.html'
    queryset = Post.objects.all()
    paginate_by = 6


class AllPostsView(ListView):
    """
    This class shows all posts, and adds the newest post on top of the page.
    The posts are ordered by date in decreasing order.
    """

    template_name = 'magazine/all_posts.html'
    queryset = Post.objects.all()


class AdminPage(LoginRequiredMixin, ListView):
    """
    This class adds all the models data in one area for the superuser.
    """

    model = Post
    template_name = 'admin_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        context['comments'] = Comment.objects.all()
        context['comments_approved'] = Comment.objects.filter(approved=True)
        context['count'] = Post.objects.all().count()
        context['comment'] = Comment.objects.all().count()
        return context


# Rouizi
class PostView(DetailView):
    """
    This class handles the detail view. When the user clicks 'read more'
    the user get redirected to post.html.
    This class also handles the comments.
    """
    model = Post
    template_name = "magazine/post.html"

    def get_context_data(self, **kwargs):
        """
        This function handles the comments that have been made.
        This function gets the primary key of a specific post.
        This function gets the comments that have been made on that post.

        """
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        slug = self.kwargs["slug"]

        form = CommentForm()
        post = get_object_or_404(Post, pk=pk, slug=slug)
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        """
        This function handles the comment form in the posts DetailView.
        When a post request is made, when a user has commented, the function gets all comments from that post.
        If the form is valid, the function saves the comment and add it to the post.
        """
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = Post.objects.filter(id=self.kwargs['pk'])[0]
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']

            comment = Comment.objects.create(
                name=name, email=email, content=content, post=post
            )

            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)


class PostCreateView(LoginRequiredMixin, CreateView):
    """
    This class handles the view where the user can write and publish a blog post.
    It gives the user fields where they can fill in a title,
    a decription of the post, post content and they can add an image.
    """
    model = Post
    fields = ['title', 'article_description', 'content', 'image']

    def get_success_url(self):
        """
        This method redirects the user to the home page.
        It also displays a message.
        """
        messages.success(
            self.request, 'Your post has been created successfully')
        return reverse_lazy('magazine:home')

# Rouizi
    def form_valid(self, form):
        """
        This method saves the model if the form is valid.
        """
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.slug = slugify(form.cleaned_data['title'])
        obj.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    """
    This class handles the view where the user can edit their blog post.
    It gives the user fields where they can change the title,
    the decription of the post, the post content and they can change the image.
    This function redirects the user to home.html when the update is done.
    """
    model = Post
    fields = ['title', 'article_description', 'content', 'image']

    # Rouizi
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update = True
        context['update'] = update

        return context

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been updated successfully')
        return reverse_lazy('magazine:home')

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """
    This class redirects the user to home.html when they have deleted their post.
    It also displays a message.
    """
    model = Post

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been deleted successfully')
        return reverse_lazy('magazine:home')

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class UserPostView(generic.ListView):
    """
    This class filters the posts made by a specific user.
    The posts are shown on user_posts.html.
    The posts are ordered by date, where the latest post is shown on top of the page.
    """
    model = Post
    template_name = 'users/user_posts.html'
    paginate_by = 2

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user).order_by('-created_on')


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    """
    This class handles the comment deleted by the admin.
    It displays a message if the deletion is successfull.
    """
    model = Comment

    def get_success_url(self):
        messages.success(
            self.request, 'Comment has been deleted successfully')
        return reverse_lazy('magazine:admin_page')


class AdminPostDeleteView(LoginRequiredMixin, DeleteView):
    """
    This class handles the posts deleted by the admin.
    It displays a message if the deletion is successfull.
    """
    model = Post
    template_name = 'magazine/admin_post_confirm_delete.html'

    def get_success_url(self):
        messages.success(
            self.request, 'Post has been deleted successfully')
        return reverse_lazy('magazine:admin_page')

templates/magazine/admin_post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_superuser %}
<div class="container form-container">
    <h3>Delete Post</h3>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this post?</p>
        <p>{{ post.title }} by {{ post.author }}</p>
        <strong>This action cannot be undone</strong>
        <a href="{% url 'magazine:admin_page' %}" class="btn btn-outline-dark">Cancel</a>
        <button class="btn btn-outline-dark" type="submit">Delete Post</button>
    </form>
</div>
{% endif %}
{% endblock %}

templates/magazine/all_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<hr>
<div class="row blog-post-container">
  {% for post in object_list %}

  <div class="col-4 post-container">
    <a class="post-image-link" href="{% url 'magazine:post' post.id post.slug %}">
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
      
    {% else %}
    <a class="post-image-link" href="{% url 'magazine:post' post.id post.slug %}">
    <img src="{% static 'images/default-post.jpg' %}" alt="{{ post.title }}" class="post-image">
  
    {% endif %}
  
    <div class="card-body">
      <span class="blog-author-date {% url 'users:profile' post.author.username %}">
        {{ post.author }} | {{ post.created_on }}
       </span>
       <div class="title-description-container">
      <h2 class="card-title">{{ post.title }}</h2>
      <h3>{{ post.article_description }}</h3>
      </div>
    </div>
  </a>
  </a>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/magazine/comment_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_superuser %}
<div class="container form-container">
    <h3>Delete Post</h3>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this comment?</p>
        <p>{{ comment.content }} by {{ comment.name }}</p>
        <strong>This action cannot be undone</strong>
        <a href="{% url 'magazine:admin_page' %}" class="btn btn-outline-dark">Cancel</a>
        <button class="btn btn-outline-dark" type="submit">Delete Comment</button>
    </form>
</div>
{% endif %}
{% endblock %}

templates/magazine/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid hero">
  <h1 class="logo">MAGAZINE</h1>
  <h2>Interior & Lifestyle</h2>
</div>
<hr>
<div class="row blog-post-container">
  {% for post in object_list %}

  <div class="col-4 post-container">
    <a class="post-image-link" href="{% url 'magazine:post' post.id post.slug %}">
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
      
    {% else %}
    <a class="post-image-link" href="{% url 'magazine:post' post.id post.slug %}">
    <img src="{% static 'images/default-post.jpg' %}" alt="{{ post.title }}" class="post-image">
  
    {% endif %}
  
    <div class="card-body">
      <span class="blog-author-date {% url 'users:profile' post.author.username %}">
        {{ post.author }} | {{ post.created_on }}
       </span>
       <div class="title-description-container">
      <h2 class="card-title">{{ post.title }}</h2>
      <h3>{{ post.article_description }}</h3>
      </div>
    </div>
  </a>
  </a>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/magazine/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="container-sm">
    <div class="post-detail-container">
  {% if post.image %}
  <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image-detail">
  {% else %}
  <img src="{% static 'images/default-post.jpg' %}" class="post-image-detail" alt="{{ post.title }}">
  {% endif %}

    <div class="post-card-body">
      <span class="blog-author-date {% url 'users:profile' post.author.username %}">
        {{ post.author }} | {{ post.created_on }}
       </span>
      <h2 class="card-title">{% block title %} {{ post.title }} {% endblock title %}</h2>
      <h3>{{ post.article_description }}</h3>
      <p class="post-detail-text">{{ post.content | safe }}</p>
      {% if post.author == request.user %}
      <div class="container">
        <a class="btn btn-outline-dark" href="{% url 'magazine:post_update' post.id %}">Edit</a>
        <a class="btn btn-outline-dark" href="{% url 'magazine:post_delete' post.id %}">Delete</a>
      </div>
      {% endif %}

    </div>
    </div>
    {% if comments %}
    <div class="row mt-5 user-comment-container">
      <div class="offset-lg-3">
        <h3>Comment{{ comments.count|pluralize }}</h3>
        <span class="badge badge-dark ml-2">{{ comments.count }}</span>
      </div>
      {% for comment in comments %}
      <div class="offset-lg-3 mt-2 user-comment">
        <div class="p-2">
          <div class="row">
            <div class="comment-content-name">
              <img class="rounded-circle mr-2" src="{% static 'images/avatar128.png' %}" alt="Avatar">
              <strong>{{ comment.name }}</strong>
            </div>
            <div class="comment-content">
              <p class="m-1 mt-3">{{ comment.content }}</p>
              <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

    <div class="row mt-5 comment-container">
      <div class="col comment-form-container">
        <h3>Leave a comment</h3>
        <form method='POST'>
          {% csrf_token %}
          <div class="form-group">
            <span class="ml-2"></span>{{ form.name.label_tag }}
            <input type="text" class="form-control input-area {% if form.name.errors %}is-invalid{% endif %}" id="id_name"
              name="name" value="{{ form.name.value|default:'' }}">
          </div>
          <div class="form-group">
            <span class="ml-2"></span>
            {{ form.email.label_tag }}
            <span class="text-muted"><small>(Your email address will not be published)</small></span>
            <input type="text" class="form-control input-area {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
              name="email" value="{{ form.email.value|default:'' }}">
          </div>
          <div class="form-group">
            <span class="ml-2"></span>{{ form.content.label_tag }}
            <textarea class="form-control input-area {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
              name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
          </div>
          <button type="submit" class="btn btn-outline-dark">Post Comment</button>
        </form>
      </div>
    </div>
  
  </div>
{% endblock content %}

templates/magazine/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container form-container">
    <h3>Delete Post</h3>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this post?</p>
        <button class="btn btn-outline-dark" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

templates/magazine/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container form-container">
    <h3>{% if update %}Update Post{% else %}Create Post{% endif %}</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            {{ form.title.label_tag }}
            <input type="text" class="form-control input-area {% if form.title.errors %}is-invalid{% endif %}"
                id="id_title" name="title" value='{{ form.title.value|default:"" }}'>

            {% if form.title.errors %}
            <div class="invalid-feedback">{{ form.title.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.article_description.label_tag }}
            <textarea placeholder="Describe what this article is about" type="text" class="form-control input-area {% if form.article_description.errors %}is-invalid{% endif %}"
                id="id_article_description" name="article_description" rows="10" cols="10">{{ form.article_description.value|default:"" }}</textarea>

            {% if form.article_description.errors %}
            <div class="invalid-feedback">{{ form.article_description.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.content.label_tag }}
            <textarea type="text" class="form-control input-area {% if form.content.errors %}is-invalid{% endif %}"
                id="id_content" name="content"
                rows="10" cols="40">{{ form.content.value|default:"" }}</textarea>
            {% if form.content.errors %}
            <div class="invalid-feedback">
                {{ form.content.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.image.label_tag }}
            <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
                accept="image/*">
            {% if form.image.errors %}
            <div class="invalid-feedback">
                {{ form.image.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.tags.label_tag }}
            <select class="form-select" aria-label="Default select example" name="tags" id="id_tags" multiple>
                {% for name, value in form.tags.field.choices %}
                <option value="{{ name }}">{{ value }}</option>
                {% endfor %}
              </select>
              {% if form.tags.errors %}
              <div class="invalid-feedback">{{ form.tags.errors }}</div>
              {% endif %}
        </div>
        <button class="btn btn-outline-dark" type="submit">
            {% if update %}Update Post{% else %}Create Post{% endif %}
        </button>
    </form>
</div>
{% endblock content %}