blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include(('magazine.urls', 'magazine'), namespace='magazine')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazine/urls.py
from django.urls import path
from .views import HomeView, PostView, PostCreateView, PostDeleteView, PostUpdateView, UserPostView, AdminPage, CommentDeleteView, AllPostsView, AdminPostDeleteView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('posts/', AllPostsView.as_view(), name='posts'),
    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('users/user-posts/', UserPostView.as_view(), name='user_posts'),
    path('admin-page/', AdminPage.as_view(), name='admin_page'),
    path('<int:pk>/admin-page/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('<int:pk>/admin-page/delete-post/', AdminPostDeleteView.as_view(), name='admin_post_delete'),
]

users/urls.py
from django.urls import path, reverse_lazy
from . views import signup, loginUser, logoutUser, profile, AboutMeForm, edit_user_profile
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profile, name='profile'),
    path('about_user/', edit_user_profile, name='about_user'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]

templates/admin_page.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_superuser %}
<div class="container-fluid">
  <h1 class="admin-title">Admin Dashboard</h1>

  <div class="info-container">
   <div class="info-card">
    <h2>Posts<br>
      {{ count }}</h2>
   </div>
      
    <div class="info-card">
    <h2>Comments<br>
      {{ comment }}</h2>
  </div>
</div>



  <div class="admin-container">
    <div class="">
      <table class="table">
        <thead>
          <tr>
          <th scope="col">Name</th>
          <th scope="col">Post title</th>
          <th scope="col">Article description</th>
          <th scope="col" class="post-content">Post Content</th>
          <th scope="col">Date</th>

        </tr>
        </thead>
        {% for post in object_list %}
        <tbody>
          <tr>
            <td scope="col">{{ post.author }}</td>
            <td scope="col">{{ post.title }}</td>
            <td scope="col">post.article_description</td>
            <td scope="col">
              <div class="dropdown">
              <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ post.title }}
              </button>
              <ul class="dropdown-menu">
                <li><p class="" href="#">{{ post.content }}</p></li>
              </ul>
            </div>
          </td>
            <td scope="col">{{ post.created_on }}</td>
            <td><a class="btn btn-outline-dark" href="{% url 'magazine:admin_post_delete' post.id %}">Delete</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>

  </div>
  
</div>
<div class="admin-container">
    <table class="table">
      <thead>
        <tr>
          
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Post title</th>
          <th scope="col">comment content </th>
          <th scope="col">comment created</th>
          
        </tr>
      </thead>
      {% for comment in comments %}

      <tbody>
        <tr>

          <td scope="col">{{ comment.name }}</td>
          <td scope="col">{{ comment.email }}</td>
          <td scope="col">{{ comment.post }}</td>
          <td scope="col">{{ comment.content }}</td>
          <td scope="col">{{ comment.created }}</td>
        
          <td><a class="btn btn-outline-dark" href="{% url 'magazine:comment_delete' comment.id %}">Delete</a></td>
        </tr>

        {% endfor %}
      </tbody>
    </table>

  </div>
</div>
{% else %}
<div class="staff-container">
  <h2>This is a staff page</h1>
</div>
{% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/215e1e67e2.js" crossorigin="anonymous"></script>
  <meta name="description" content="Magazine, where people share and get inspired by interior designs.">
  <meta name="keywords" content="interior design, interior, interior articles, design, trends">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/CSS/style.css">
  <link type="image/png" sizes="32x32" rel="icon" href="static/images/favicon/favicon.ico">
  <title>Magazine</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'magazine:home' %}">Magazine</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'magazine:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'magazine:posts' %}">Blog</a>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.user.username in request.path %}active{% endif %}"
              href="{% url 'users:profile' request.user.username %}">Profile</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'magazine:post_create' %}"
              class="nav-link {% if request.path == '/post/create/' %}active{% endif %}">Create Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a href="{% url 'magazine:admin_page' %}"
              class="nav-link {% if request.path == '/admin_page/' %}active{% endif %}">Admin</a>
          </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
            <a href="{% url 'users:login' %}"
              class="nav-link {% if request.path == '/users/login/' %}active{% endif %}">Log in</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'users:signup' %}"
              class="nav-link {% if request.path == '/users/signup/' %}active{% endif %}">Signup</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>

  </nav>

  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}



  {% block content %}
  {% endblock content %}

  <footer>
    <div class="card text-center">
      <div class="card-header">
        MAGAZINE
      </div>
      <div class="footer-container">
        <div id="social-media">
          <ul class="social-media-container footer-links">
            <li>
              <a href="https://www.instagram.com/" rel="noopener" target="_blank"
                aria-label="Visit our instagram page (opens in a new tab)"><i class="fa-brands fa-instagram"></i></a>
            </li>
            <li>
              <a href="https://www.facebook.com/" rel="noopener" target="_blank"
                aria-label="Visit our facebook page (opens in a new tab)"><i class="fa-brands fa-facebook"></i></a>
            </li>
            <li>
              <a href="https://www.twitter.com/" rel="noopener" target="_blank"
                aria-label="Visit our twitter page (opens in a new tab)"><i class="fa-brands fa-twitter"></i></a>
            </li>
            <li>
              <a href="https://www.youtube.com/" rel="noopener" target="_blank"
                aria-label="Visit our youtube page (opens in a new tab)"><i class="fa-brands fa-youtube"></i></a>
            </li>

          </ul>
        </div>
      </div>
      <div class="card-footer">
        &copy;Copyright 2022<br>
        Website created by Frirsta. App icon by <a href="https://icons8.com/">Icon8</a>

      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
    integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous">
  </script>
</body>

</html>