blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include(('magazine.urls', 'magazine'), namespace='magazine')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazine/urls.py
from django.urls import path
from .views import HomeView, PostView, PostCreateView, PostDeleteView, PostUpdateView, UserPostView, AdminPage, CommentDeleteView, AllPostsView, AdminPostDeleteView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('posts/', AllPostsView.as_view(), name='posts'),
    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('users/user-posts/', UserPostView.as_view(), name='user_posts'),
    path('admin-page/', AdminPage.as_view(), name='admin_page'),
    path('<int:pk>/admin-page/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('<int:pk>/admin-page/delete-post/', AdminPostDeleteView.as_view(), name='admin_post_delete'),
]

users/urls.py
from django.urls import path, reverse_lazy
from . views import signup, loginUser, logoutUser, profile, AboutMeForm, edit_user_profile
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profile, name='profile'),
    path('about_user/', edit_user_profile, name='about_user'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField('email adress', unique=True)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']


# Rouizi
class Profile(models.Model):
    about_me = models.TextField()
    image = models.ImageField(upload_to='profile_image', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


# Rouizi
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# Rouizi
class AboutMeForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)

    def __init__(self, og_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.og_username = og_username

    def clean_username(self):
        """
        Throws exception if username is taken.
        """

        username = self.cleaned_data['username']
        if username != self.og_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'Username already exists.')
        return username

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from .models import User, Profile
from .forms import SignUpForm, LoginForm, AboutMeForm
from django.contrib import messages


def signup(request):
    """
    This function handles the signup form.
    This function creates a User instance.
    The user is logged in with the login() funtion.
    When user is created they get redirected to home.html.

    """
    # Rouizi
    if request.user.is_authenticated:
        return redirect('magazine:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            messages.success(request, "You are now a registered user!")
            return redirect("magazine:home")
    else:
        form = SignUpForm()
    return render(request, "users/signup.html", {"form": form})


def loginUser(request):
    """
    This functions handles the login form.
    When they user logs in they get redirected to home.html.
    This function dispays a message on the page if the username or password is incorrect.
    """
    if request.user.is_authenticated:
        return redirect("magazine:home")
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect("magazine:home")
            else:
                messages.error(request, 'Invalid username or password')
    else:
        form = LoginForm()

    return render(request, "users/login.html", {"form": form})


def logoutUser(request):
    """
    This function redirects the user to login page when the user logs out.
    """
    logout(request)
    return redirect(reverse("users:login"))


# Rouizi
@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'users/profile.html', {'profile': profile, 'user': user})


# Rouizi
@login_required
def edit_user_profile(request):
    if request.method == 'POST':
        form = AboutMeForm(request.user.username, request.POST, request.FILES)
        if form.is_valid():
            about_me = form.cleaned_data["about_me"]
            username = form.cleaned_data["username"]
            image = form.cleaned_data["image"]

            user = User.objects.get(id=request.user.id)
            profile = Profile.objects.get(user=user)
            user.username = username
            user.save()
            profile.about_me = about_me
            if image:
                profile.image = image
            profile.save()
            return redirect("users:profile", username=user.username)
    else:
        form = AboutMeForm(request.user.username)
    return render(request, "users/about_user.html", {"form": form})

templates/users/about_user.html
{% extends 'base.html' %}

<h2>Edit Profile</h2>
{% block content %}
<div class="container form-container">
    <h3>Edit Profile</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            <input type="text" class="form-control input-area {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
                name="username" value="{{ form.username.value|default:user.username }}">
            {% if form.username.errors %}
            <div class="invalid-feedback">
                {{ form.username.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.about_me.label_tag }}
            <textarea type="text" class="form-control input-area {% if form.about_me.errors %}is-invalid{% endif %}"
                id="id_about_me" name="about_me" value="{{ form.about_me.value }}"
                rows="5"></textarea>
            {% if form.about_me.errors %}
            <div class="invalid-feedback">
                {{ form.about_me.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.image.label_tag }}
            <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
                accept="image/*">
            {% if form.image.errors %}
            <div class="invalid-feedback">
                {{ form.image.errors }}
            </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-outline-dark">Submit</button>
    </form>
</div>

{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="login-container form-container">
        <h3>Login</h3>
        <form method="POST" class="form login-form">
            {% csrf_token %}

            <div class="form-group">
                {{ form.username.label_tag }}
                <input type="text" class="form-control input-area {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
                    name="username" value='{{ form.username.value|default:"" }}'>
                <small class="text-muted">{{ form.username.help_text }}</small>
                {% if form.username.errors %}
                <div class="invalid-feedback">{{ form.username.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                <input type="password" class="form-control input-area {% if form.password.errors %}is-invalid{% endif %}" id="id_password"
                    name="password" value='{{ form.password.value|default:"" }}'>

                {% if form.password.errors %}
                <div class="invalid-feedback">{{ form.password.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-outline-dark">Sign in</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/users/password_change.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="card form-container">
        <h3>Change password</h3>
        <form method="POST">
            {% csrf_token %}

            <div class="form-group">
                {{ form.old_password.label_tag }}
                <input type="password" class="form-control input-area {% if form.old_password.errors %}is-invalid{% endif %}"
                    id="id_old_password" name="old_password" value='{{ form.old_password.value|default:"" }}'>

                {% if form.old_password.errors %}
                <div class="invalid-feedback">{{ form.old_password.errors }}</div>
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.new_password1.label_tag }}
                <input type="password" class="form-control input-area {% if form.new_password1.errors %}is-invalid{% endif %}"
                    id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>

                {% if form.new_password1.errors %}
                <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
                {% endif %}
                <small class="text-muted">{{ form.new_password1.help_text }}</small>
            </div>
            <div class="form-group">
                {{ form.new_password2.label_tag }}
                <input type="password" class="form-control input-area {% if form.new_password2.errors %}is-invalid{% endif %}"
                    id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>

                {% if form.new_password2.errors %}
                <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
                {% endif %}

            </div>



            <button type="submit" class="btn btn-outline-dark">Change password</button>
        </form>
    </div>
</div>


{% endblock content %}

templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <div class="alert alert-success" role="alert">
            Your password has been changed successfully!
          </div>
          <a href="{% url 'magazine:home' %}" class="btn btn-outline-dark">Return to home page</a>
    </div>
</div>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="profile-outer">
<div class="profile-container">
  {% if user.profile.image %}
  <div class="profile-picture">
  <img src="{{ profile.image.url }}" class="card-img-top" alt="{{ user.username }}">
  {% else %}
  <img src="{% static 'images/avatar.png' %}" class="card-img-top" alt="{{ user.username }}">
  {% endif %}
</div>
    <h3>{{ user.username }}</h3>
    <p class="card-text">{{ user.profile.about_me }}</p>
  </div>
  <div class="profile-links">
    <p><a class="btn btn-outline-dark" href="{% url 'users:about_user' %}">Edit About Text</a></p>
  <p><a class="btn btn-outline-dark" href="{% url 'users:password_change' %}">Change Password</a></p>
  <p><a class="btn btn-outline-dark" href="{% url 'magazine:user_posts' %}">My Posts</a></p>
</div>
</div>

{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}
{% block content %}


<div class="container"></div>
<div class="form-container">
    <h3>Signup</h3>
    <form method="POST" class="form signup-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            <input type="text" class="form-control input-area {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
                name="username" value='{{ form.username.value|default:"" }}'>
            <small class="text-muted">{{ form.username.help_text }}</small>
            {% if form.username.errors %}
            <div class="invalid-feedback">{{ form.username.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control input-area {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
                name="email" value='{{ form.email.value|default:"" }}'>
            <small class="text-muted">{{ form.email.help_text }}</small>
            {% if form.email.errors %}
            <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password1.label_tag }}
            <input type="password" class="form-control input-area {% if form.password1.errors %}is-invalid{% endif %}"
                id="id_password1" name="password1" value='{{ form.password1.value|default:"" }}'>
            <small class="text-muted">{{ form.password1.help_text }}</small>
            {% if form.password1.errors %}
            <div class="invalid-feedback">{{ form.password1.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }}
            <input type="password" class="form-control input-area {% if form.password2.errors %}is-invalid{% endif %}"
                id="id_password2" name="password2" value='{{ form.password2.value|default:"" }}'>
            <small class="text-muted">{{ form.password2.help_text }}</small>
            {% if form.password2.errors %}
            <div class="invalid-feedback">{{ form.password2.errors }}</div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-outline-dark">Signup</button>
    </form>
</div>
</div>
</div>
{% endblock content %}

templates/users/user_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
  <h2>My Posts</h2>
  {% if user.is_authenticated %}
  <div class="user-post-container">
    {% for post in object_list %}
  
    <div class="post-container">
      <a class="post-image-link" href="{% url 'magazine:post' post.id post.slug %}">
      {% if post.image %}
      <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
        
      {% else %}
      <a class="post-image-link" href="{% url 'magazine:post' post.id post.slug %}">
      <img src="{% static 'images/default-post.jpg' %}" alt="{{ post.title }}" class="post-image">
    
      {% endif %}
    
      <div class="card-body">
        <span class="blog-author-date {% url 'users:profile' post.author.username %}">
          {{ post.author }} | {{ post.created_on }}
         </span>
         <div class="title-description-container">
        <h2 class="card-title">{{ post.title }}</h2>
        <h3>{{ post.article_description }}</h3>
        </div>
      </div>
    </a>
    </a>
    </div>
    {% endfor %}
  </div>
  
  {% endif %}
</div>
{% endblock content %}